################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &Orderer
      Name: OrdererMSP
      ID: OrdererMSP
      MSPDir: crypto-config/peerOrganizations/orderer.example.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"

      AnchorPeers:

    - &Pharma
      Name: PharmaMSP
      ID: PharmaMSP
      MSPDir: crypto-config/peerOrganizations/pharma.example.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PharmaMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('PharmaMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('PharmaMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('PharmaMSP.member')"

      AnchorPeers:
          - Host: peer0.pharma.example.com
            Port: 7041

    - &Hospital
      Name: HospitalMSP
      ID: HospitalMSP
      MSPDir: crypto-config/peerOrganizations/hospital.example.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('HospitalMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('HospitalMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('HospitalMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('HospitalMSP.member')"

      AnchorPeers:
          - Host: peer0.hospital.example.com
            Port: 7061

    - &IoTTracker
      Name: IoTTrackerMSP
      ID: IoTTrackerMSP
      MSPDir: crypto-config/peerOrganizations/tracker.example.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('IoTTrackerMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('IoTTrackerMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('IoTTrackerMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('IoTTrackerMSP.member')"

      AnchorPeers:
          - Host: peer0.tracker.example.com
            Port: 7081

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &Group1Defaults
    OrdererType: solo
    Addresses:
        - orderer0.group1.orderer.example.com:7030
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group group1 #
    Group1Genesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orderer
                    - *Pharma
                    - *Hospital
                    - *IoTTracker

    # Profile used to create channeltx for supply #
    Supply:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Pharma
                    - *Hospital
                    - *IoTTracker
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Pharma
                - *Hospital
                - *IoTTracker
